# 2.2 Знаходження власних значень і власних векторів  матриць
---------------------

Нехай $A\in \mathbb{R}^n(\mathbb{C})$ -- яка-небудь матриця. Число $\lambda$ називається
*власним значенням* матриці $A$, якщо існує ненульовий вектор $v\in \mathbb{C}^n$ такий, що
виконується рівність

$(1)\qquad\qquad\qquad 
Av=\lambda v.$

Тоді вектор $v$ називається *власним вектором*, який відповідає власному значенню $\lambda$.

Для знаходження власних значень і власних векторів матриць можна використати бібліотечну функцію ``eig``, яка належить модулю ``linalg``, що є частиною бібліотеки ``scipy``. 

Першим аргументом функції ``eig`` є матриця. Якщо решту аргументів прийняти за замовчуванням, то результатом виконання цієї функції є два ``numpy.ndarray`` масиви:
        - вектор, елементами якого є власні числа, 
        - матриця, стовпцями якої є власні вектори, впорядковані за порядком відповідних власних значень у попередньому векторі. 

#### Пояснення до використання програмного коду
-----------------

*   Підготувати обчислювальне середовище і потрібні функції :
    1. виконати комірку для підготовки середовища, зокрема імпортувати модуль ``linalg``
    2. виконати комірку, де **визначена** функція ``eigenvalue_problem_solver``
   
*   Обчислити власні числа і власні вектори заданої СЛАР :
    1. виконати комірку, де визначена функція ``set_matrix`` 
    2. Виконати комірку з викликом функції  ``eigenvalue_problem_solver`` 


#### Програмна реалізація методів
------------

>#### Підготовка середовища

In [1]:
import numpy as np
from scipy import linalg

>#### ``eigenvalue_problem_solver`` -- функція, яка визначає процес обчислення власних значень та векторів матриці за допомогою ``linalg.eig``

In [2]:
def eigenvalue_problem_solver(n, matrix):
    """ функція для задання конкретної матриці  """
    eig_values, eig_vectors = linalg.eig(matrix(n))
    return eig_values, eig_vectors.T

>#### ``residual_calc`` -- функція для обчислення нев'язки $residual := A v - \lambda v$  після пістановки власних значень та відповідних власних векторів матриці у рівняння (1)

In [3]:
def residual_calc(matrix,eig_values,eig_vector):
    for i in range(matrix.shape[0]):
        residual = linalg.norm(matrix.dot(eig_vector[i,:]) - eig_values[i]*eig_vector[i,:])
        print(f"i={i}, residual={residual}")

#### Обчислювальні експерименти
------------

Продемонструємо на прикладах застосування функції ``linalg.eig`` для обчислення власних значень та векторів квадратних матриць.

**Приклад 1.** (example 5.3) Обчислити власні значення та вектори матриці
$\qquad
A=
\begin{pmatrix}
15 & -2 &  2 \\
1  & 10 & -3 \\
-2 &  1 & 0
\end{pmatrix}
$.

Визначимо функцію для задання матриці

In [4]:
def set_matrix(n):
    """ функція для задання конкретної матриці  """
    return np.array([[15,  - 2,  2], [ 1,  10 , -3], [ -2, 1, 0]],dtype=float)

In [5]:
lmbds, vs = eigenvalue_problem_solver(3,set_matrix)
vs

array([[-0.08811726,  0.30873868,  0.94705637],
       [-0.94359219, -0.31169403,  0.11171665],
       [ 0.39292879,  0.91947889,  0.01286632]])

In [6]:
print(f'Власні числа: \n{lmbds} ')   

Власні числа: 
[ 0.51208483+0.j 14.10255576+0.j 10.38535941+0.j] 


In [7]:
print(f'Власні вектори: \n{vs} ')   

Власні вектори: 
[[-0.08811726  0.30873868  0.94705637]
 [-0.94359219 -0.31169403  0.11171665]
 [ 0.39292879  0.91947889  0.01286632]] 


Переконаємося, що для кожного з отриманих власних значень і відповідних власних векторів нев'язка буде малою:

In [8]:
residual_calc(set_matrix(3),lmbds,vs)

i=0, residual=1.5207579772826452e-15
i=1, residual=2.5219419200973697e-15
i=2, residual=3.5658083926151344e-15


**Приклад 2.** Обчислити власні значення та вектори матриці Гільберта різних розмірів (див.приклади розв'язування методом Гаусса).

Визначимо функцію, яка генеруватиме матрицю Гільберта:

In [9]:
def H_matrix(n):
    """ функція для задання матриці Гільберта"""   
    a = np.empty((n,n),dtype=float)
    for i in range(n):
        for j in range(n):
            a[i,j] = 1/(i+j+1) 
    return a

Обчислимо власні значення та вектори матриці Гільберта для різних значень ``n``.

In [10]:
n=3
Hvals, Hvects = eigenvalue_problem_solver(n,H_matrix)

In [11]:
print(f'Власні числа: \n{Hvals} ')   

Власні числа: 
[1.40831893+0.j 0.12232707+0.j 0.00268734+0.j] 


In [12]:
print(f'Власні вектори: \n{Hvects} ')   

Власні вектори: 
[[ 0.82704493  0.4598639   0.32329844]
 [ 0.54744843 -0.52829024 -0.64900666]
 [ 0.12765933 -0.71374689  0.68867153]] 


In [13]:
n=5
Hvals, Hvects = eigenvalue_problem_solver(n,H_matrix)

In [14]:
print(f'Власні числа: \n{Hvals} ')   

Власні числа: 
[1.56705069e+00+0.j 2.08534219e-01+0.j 1.14074916e-02+0.j
 3.05898040e-04+0.j 3.28792877e-06+0.j] 


In [15]:
print(f'Власні вектори: \n{Hvects} ')   

Власні вектори: 
[[-0.76785474 -0.44579106 -0.32157829 -0.25343894 -0.20982264]
 [-0.60187148  0.27591342  0.42487662  0.44390304  0.42901335]
 [-0.21421362  0.72410213  0.12045328 -0.30957397 -0.56519341]
 [-0.04716181  0.43266733 -0.66735044 -0.23302452  0.55759995]
 [ 0.00617386 -0.11669275  0.50616366 -0.76719119  0.37624555]] 


In [16]:
n=10
Hvals, Hvects = eigenvalue_problem_solver(n,H_matrix)

In [17]:
print(f'Власні числа: \n{Hvals} ')   

Власні числа: 
[1.75191967e+00+0.j 3.42929548e-01+0.j 3.57418163e-02+0.j
 2.53089077e-03+0.j 1.28749614e-04+0.j 4.72968929e-06+0.j
 1.22896774e-07+0.j 2.14743882e-09+0.j 2.26674554e-11+0.j
 1.09322786e-13+0.j] 


In [18]:
print(f'Власні вектори: \n{Hvects} ')   

Власні вектори: 
[[ 6.99514891e-01  4.25998913e-01  3.16976988e-01  2.55523006e-01
   2.15277840e-01  1.86578238e-01  1.64946526e-01  1.47992143e-01
   1.34310446e-01  1.23016713e-01]
 [ 6.37640842e-01 -7.04371051e-02 -2.33556605e-01 -2.82108835e-01
  -2.93657165e-01 -2.90981823e-01 -2.82497991e-01 -2.71744237e-01
  -2.60323765e-01 -2.48988410e-01]
 [-3.03404206e-01  5.99560151e-01  3.78571505e-01  1.44313674e-01
  -2.74969528e-02 -1.46916578e-01 -2.29138818e-01 -2.85631577e-01
  -3.24264002e-01 -3.50361227e-01]
 [ 1.05515795e-01 -5.76271783e-01  2.01933680e-01  4.12043529e-01
   3.51322220e-01  1.95432922e-01  1.93990025e-02 -1.47212403e-01
  -2.94208926e-01 -4.19514164e-01]
 [-2.93126764e-02  3.22879147e-01 -5.83114115e-01 -1.69552768e-01
   2.29493333e-01  3.74836695e-01  3.09362024e-01  1.12143643e-01
  -1.54211321e-01 -4.48204956e-01]
 [-6.67484774e-03  1.27505803e-01 -4.97391459e-01  4.10971927e-01
   3.63294163e-01 -4.87344006e-02 -3.43217612e-01 -3.52928835e-01
  -7.57666942e-0

Можна переконатися, що для кожного з отриманих власних значень і відповідних власних векторів нев'язка буде малою. Наприклад, нев'язка для останнього результату буде такою:

In [19]:
residual_calc(H_matrix(10),Hvals,Hvects)

i=0, residual=1.0448048107080504e-15
i=1, residual=5.114581455958995e-16
i=2, residual=2.262086438359439e-16
i=3, residual=1.8628763940619207e-16
i=4, residual=1.0494865757486728e-16
i=5, residual=3.245010027011731e-16
i=6, residual=1.162316126507303e-16
i=7, residual=4.8236658328790986e-17
i=8, residual=5.4402650311295894e-17
i=9, residual=3.055098308349397e-17


На завершення ще розглянемо число обумовленості розглянутих матриць, яке обчислюють за формулою $K(A):=\frac{|\lambda_{max}|}{|\lambda_{min}|}$, де $\lambda_{max}$ і $\lambda_{min}$ -- максимальне і мінімальне за абсолютною величиною власні значення матриці $A$. Матимемо $K(A_3)\approx 5\times 10^2$, $K(A_5)\approx 10^5$ і $K(A_{10})\approx 10^{13}$ при розмірах $n=3$, $n=5$ і $n=10$ відповідно, що означає погану обумовленість матриць Гільберта вже при невеликих розмірах. Відомо, що чисельне розв'язування таких систем є проблематичним. 

Отож, приходимо до висновку, що за допомогою бібліотечної функції ``linalg.eig`` можна обчислювати власні значення і власні вектори матриць з великою точністю. При чисельному розв'язуванні СЛАР таким шляхом можна дослідити обумовленість відповідних матриць.